import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "de" | "en";
const LANG_KEY = "pref_language";

const de: Record<string, string> = {
  "nav.home": "Übersicht",
  "nav.trips": "Fahrten",
  "nav.profile": "Profil",
  "common.save": "Speichern",
  "common.cancel": "Abbrechen",
  "common.done": "Fertig",
  "common.edit": "Bearbeiten",
  "common.close": "Schließen",
  "profile.title": "Profil",
  "profile.editBtn": "Profil bearbeiten",
  "profile.plate": "Kennzeichen",
  "profile.account": "Konto",
  "profile.sync": "Sync",
  "profile.synced": "Synchronisiert",
  "profile.offline": "Offline",
  "profile.premium": "Premium",
  "section.account": "Konto",
  "section.tracking": "Tracking & Fahrterkennung",
  "section.settings": "Einstellungen",
  "section.security": "Sicherheit & Datenschutz",
  "section.support": "Support",
  "row.personalData": "Persönliche Daten",
  "row.vehicleProfile": "Fahrprofil & Fahrzeugdaten",
  "row.autoTracking": "Automatisches Tracking",
  "row.autoTracking.desc": "Fahrten automatisch erkennen und aufzeichnen",
  "row.gpsTracking": "GPS-Tracking",
  "row.gpsTracking.desc": "Standort während einer Fahrt erfassen",
  "row.bgTracking": "Hintergrund-Tracking",
  "row.bgTracking.desc": "Fahrten auch bei geschlossener App erkennen",
  "row.offline": "Offline-Speicherung",
  "row.offline.desc": "Fahrten ohne Internet zwischenspeichern",
  "row.pauseTracking": "Tracking pausieren",
  "row.pauseTracking.desc": "Aufzeichnung vorübergehend deaktivieren",
  "row.notifications": "Benachrichtigungen",
  "row.defaultTripType": "Standard-Fahrtart",
  "row.language": "Sprache",
  "row.design": "Design",
  "row.changePassword": "Passwort ändern",
  "row.privacy": "Datenschutz",
  "row.faceId": "Face ID / App-Sperre",
  "row.faq": "Hilfe & FAQ",
  "row.contact": "Kontakt",
  "row.appVersion": "App-Version",
  "row.logout": "Abmelden",
  "row.deleteAccount": "Konto löschen",
  "deleteAccount.title": "Konto unwiderruflich löschen?",
  "deleteAccount.message": "Alle deine Fahrten, dein Profil und alle Kontodaten werden sofort und dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
  "deleteAccount.confirm": "Ja, Konto löschen",
  "deleteAccount.cancel": "Abbrechen",
  "deleteAccount.error": "Konto konnte nicht gelöscht werden. Bitte versuche es erneut.",
  "tripType.business": "Geschäftlich",
  "tripType.private": "Privat",
  "theme.light": "Hell",
  "theme.dark": "Dunkel",
  "theme.system": "Systemeinstellung",
  "lang.de": "Deutsch",
  "lang.en": "Englisch",
  "lang.title": "Sprache wählen",
  "vehicle.title": "Fahrprofil & Fahrzeugdaten",
  "vehicle.brand": "Marke",
  "vehicle.model": "Modell",
  "vehicle.year": "Baujahr",
  "vehicle.color": "Farbe",
  "vehicle.plate": "Kennzeichen",
  "vehicle.brandPlaceholder": "z. B. BMW, VW, Mercedes",
  "vehicle.modelPlaceholder": "z. B. 3er, Golf, C-Klasse",
  "vehicle.yearPlaceholder": "z. B. 2022",
  "vehicle.colorPlaceholder": "z. B. Schwarz, Weiß, Blau",
  "notif.title": "Benachrichtigungen",
  "notif.general": "Allgemeine Hinweise",
  "notif.general.desc": "App-Updates und allgemeine Infos",
  "notif.trips": "Fahrten-Erinnerungen",
  "notif.trips.desc": "Hinweise zu offenen oder unvollständigen Fahrten",
  "notif.tracking": "Automatische Tracking-Hinweise",
  "notif.tracking.desc": "Statusmeldungen bei automatischer Fahrterkennung",
  "notif.gps": "GPS-Status",
  "notif.gps.desc": "Warnungen bei schwachem oder fehlendem GPS-Signal",
  "notif.offline": "Offline-Modus",
  "notif.offline.desc": "Hinweise bei fehlender Internetverbindung",
  "notif.sync": "Synchronisation",
  "notif.sync.desc": "Meldungen zu Datensynchronisation und Backup",
  "notif.login": "Login & Gerätezugriff",
  "notif.login.desc": "Sicherheitshinweise zu Anmeldungen und Gerätezugriffen",
  "notif.datenschutz": "Datenschutz & App-Sperre",
  "notif.datenschutz.desc": "Hinweise zu Datenschutzeinstellungen und App-Sperre",
  "notif.driveRemind": "Fahrt-Erinnerungen",
  "notif.driveRemind.desc": "Benachrichtigung wenn du anfaengst oder aufhoerst zu fahren",
  "privacy.title": "Datenschutz",
  "faq.title": "Hilfe & FAQ",
  "settings.title": "Einstellungen",
  "pw.step1": "Code anfordern",
  "pw.step2": "Code & Passwort",
  "pw.sendCode": "Code per E-Mail senden",
  "pw.sending": "Senden…",
  "pw.changeBtn": "Passwort ändern",
  "pw.changing": "Wird geändert…",
  "pw.newCode": "Neuen Code anfordern",
  "editProfile.title": "Profil bearbeiten",
  "editProfile.name": "Name",
  "editProfile.plate": "Kennzeichen",
  "logout.confirm": "Wirklich abmelden?",
  "logout.yes": "Abmelden",
  "logout.cancel": "Abbrechen",
  "coming.soon": "Demnächst",
  "coming.soon.desc": "Diese Funktion wird in einer zukünftigen Version verfügbar sein.",
  "contact.email": "support@fahrtdoc.de",
  "contact.title": "Kontakt",
  "contact.text": "Bei Fragen oder Problemen stehen wir dir gerne zur Verfügung.",
  "contact.emailLabel": "E-Mail Support",
  "contact.websiteLabel": "Website",
  "home.greeting": "Hallo,",
  "home.defaultDriver": "Fahrer",
  "home.quickStart": "Schnellstart",
  "home.businessTrip": "Geschäftsreise",
  "home.businessSub": "Arbeit & Dienst",
  "home.privateTrip": "Private Fahrt",
  "home.privateSub": "Persönlich",
  "home.gpsBlocked": "GPS blockiert – Simulation aktiv",
  "home.stats": "Statistiken",
  "home.period.1": "1 Mon.",
  "home.period.3": "3 Mon.",
  "home.period.6": "6 Mon.",
  "home.period.12": "Dieses Jahr",
  "home.totalKm": "Gesamt km",
  "home.trips": "Fahrten",
  "home.driveDuration": "Fahrzeit",
  "home.businessShort": "Geschäftl.",
  "home.privateShort": "Privat",
  "home.distribution": "Zweckverteilung",
  "home.recentTrips": "Letzte Fahrten",
  "home.noTrips": "Keine Fahrten in diesem Zeitraum",
  "home.startTripSuffix": "starten?",
  "home.modalSub": "GPS wird aktiviert und die Strecke automatisch aufgezeichnet.",
  "home.startBtn": "Fahrt starten",
  "history.today": "Heute",
  "history.yesterday": "Gestern",
  "history.resetFilter": "Filter zurücksetzen",
  "history.dateRange": "Von – Bis",
  "history.all": "Alle",
  "history.lastMonth": "Letzter Monat",
  "history.threeMonths": "3 Monate",
  "history.sixMonths": "6 Monate",
  "history.thisYear": "Dieses Jahr",
  "history.from": "Von",
  "history.to": "Bis",
  "history.datePlaceholder": "TT.MM.JJJJ",
  "history.clearFilter": "Filter löschen",
  "history.selected": "ausgewählt",
  "history.totalDistance": "Gesamtstrecke",
  "history.selection": "Auswahl",
  "history.of": "von",
  "history.noSelection": "Keine Fahrten ausgewählt",
  "history.noSelectionMsg": "Bitte wähle mindestens eine Fahrt aus oder verlasse den Auswahlmodus.",
  "history.noTripsTitle": "Keine Fahrten",
  "history.noTripsMsg": "Keine Fahrten für den gewählten Filter.",
  "history.selectAll": "Alle",
  "history.selectNone": "Keine",
  "auth.tagline": "Einfach fahren, clever erfassen",
  "auth.login": "Anmelden",
  "auth.register": "Registrieren",
  "auth.fullName": "Vollständiger Name",
  "auth.password": "Passwort",
  "auth.forgotPassword": "Passwort vergessen?",
  "auth.createAccount": "Konto erstellen",
  "auth.error.allFields": "Bitte alle Felder ausfüllen.",
  "auth.error.shortPassword": "Passwort muss mindestens 6 Zeichen lang sein.",
  "auth.error.emailPassword": "Bitte E-Mail und Passwort eingeben.",
  "auth.error.emailExists": "Diese E-Mail-Adresse ist bereits registriert.",
  "auth.error.notFound": "Kein Konto mit dieser E-Mail-Adresse gefunden.",
  "auth.error.wrongPassword": "Falsches Passwort. Bitte versuche es erneut.",
  "auth.hint.login": "Noch kein Konto? Jetzt registrieren.",
  "auth.hint.register": "Alle Daten werden lokal gespeichert.",
  "auth.emailLabel": "E-Mail",
  "auth.emailPlaceholder": "email@beispiel.de",
  "auth.namePlaceholder": "Max Mustermann",
  "auth.platePlaceholder": "B-DL 1234",
  "error.title": "Fehler",
  "error.nameRequired": "Bitte gib einen Namen ein.",
  "pw.error.noCode": "Bitte gib den Code ein.",
  "pw.error.tooShort": "Das Passwort muss mindestens 8 Zeichen haben.",
  "pw.error.mismatch": "Die Passwoerter stimmen nicht ueberein.",
  "pw.error.sendFailed": "Fehler beim Senden des Codes.",
  "pw.error.invalid": "Ungueltiger Code oder Fehler.",
  "pw.success.title": "Erfolg",
  "pw.success.text": "Dein Passwort wurde geaendert.",
  "pause.dialog.title": "Zwischenstopp erfassen?",
  "pause.dialog.message": "Möchtest du den aktuellen Standort als Zwischenstopp speichern?",
  "pause.withWaypoint": "Ja, als Zwischenstopp speichern",
  "pause.withoutWaypoint": "Nein, nur pausieren",
  "waypoint.label": "Zwischenstopp",
  "waypoint.addressUnavailable": "Adresse nicht verfügbar",
  "waypoint.locating": "Standort wird ermittelt…",
  "waypoint.note.title": "Notiz zum Stopp",
  "waypoint.note.placeholder": "z. B. Kundenbesuch, Ladestation …",
  "waypoint.note.confirm": "Stopp speichern",
  "waypoint.note.skip": "Ohne Notiz speichern",
  "trip.syncPending": "Route sync",
  "trip.syncRetrying": "Wird sync…",
};

const en: Record<string, string> = {
  "nav.home": "Overview",
  "nav.trips": "Trips",
  "nav.profile": "Profile",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.done": "Done",
  "common.edit": "Edit",
  "common.close": "Close",
  "profile.title": "Profile",
  "profile.editBtn": "Edit Profile",
  "profile.plate": "License Plate",
  "profile.account": "Account",
  "profile.sync": "Sync",
  "profile.synced": "Synced",
  "profile.offline": "Offline",
  "profile.premium": "Premium",
  "section.account": "Account",
  "section.tracking": "Tracking & Trip Detection",
  "section.settings": "Settings",
  "section.security": "Security & Privacy",
  "section.support": "Support",
  "row.personalData": "Personal Data",
  "row.vehicleProfile": "Driving Profile & Vehicle Data",
  "row.autoTracking": "Automatic Tracking",
  "row.autoTracking.desc": "Automatically detect and record trips",
  "row.gpsTracking": "GPS Tracking",
  "row.gpsTracking.desc": "Record location during a trip",
  "row.bgTracking": "Background Tracking",
  "row.bgTracking.desc": "Detect trips even when the app is closed",
  "row.offline": "Offline Storage",
  "row.offline.desc": "Save trips without internet connection",
  "row.pauseTracking": "Pause Tracking",
  "row.pauseTracking.desc": "Temporarily disable recording",
  "row.notifications": "Notifications",
  "row.defaultTripType": "Default Trip Type",
  "row.language": "Language",
  "row.design": "Appearance",
  "row.changePassword": "Change Password",
  "row.privacy": "Privacy",
  "row.faceId": "Face ID / App Lock",
  "row.faq": "Help & FAQ",
  "row.contact": "Contact",
  "row.appVersion": "App Version",
  "row.logout": "Sign Out",
  "row.deleteAccount": "Delete Account",
  "deleteAccount.title": "Permanently delete account?",
  "deleteAccount.message": "All your trips, profile and account data will be immediately and permanently deleted. This action cannot be undone.",
  "deleteAccount.confirm": "Yes, delete account",
  "deleteAccount.cancel": "Cancel",
  "deleteAccount.error": "Account could not be deleted. Please try again.",
  "tripType.business": "Business",
  "tripType.private": "Private",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "theme.system": "System",
  "lang.de": "German",
  "lang.en": "English",
  "lang.title": "Choose Language",
  "vehicle.title": "Driving Profile & Vehicle Data",
  "vehicle.brand": "Brand",
  "vehicle.model": "Model",
  "vehicle.year": "Year",
  "vehicle.color": "Color",
  "vehicle.plate": "License Plate",
  "vehicle.brandPlaceholder": "e.g. BMW, VW, Mercedes",
  "vehicle.modelPlaceholder": "e.g. 3 Series, Golf, C-Class",
  "vehicle.yearPlaceholder": "e.g. 2022",
  "vehicle.colorPlaceholder": "e.g. Black, White, Blue",
  "notif.title": "Notifications",
  "notif.general": "General Notices",
  "notif.general.desc": "App updates and general info",
  "notif.trips": "Trip Reminders",
  "notif.trips.desc": "Notices for open or incomplete trips",
  "notif.tracking": "Auto Tracking Notices",
  "notif.tracking.desc": "Status updates for automatic trip detection",
  "notif.gps": "GPS Status",
  "notif.gps.desc": "Warnings for weak or missing GPS signal",
  "notif.offline": "Offline Mode",
  "notif.offline.desc": "Notices when internet connection is unavailable",
  "notif.sync": "Synchronization",
  "notif.sync.desc": "Messages about data sync and backup",
  "notif.login": "Login & Device Access",
  "notif.login.desc": "Security notices for logins and device access",
  "notif.datenschutz": "Privacy & App Lock",
  "notif.datenschutz.desc": "Notices about privacy settings and app lock",
  "notif.driveRemind": "Drive Reminders",
  "notif.driveRemind.desc": "Notification when you start or stop driving",
  "privacy.title": "Privacy",
  "faq.title": "Help & FAQ",
  "settings.title": "Settings",
  "pw.step1": "Request Code",
  "pw.step2": "Code & Password",
  "pw.sendCode": "Send Code by Email",
  "pw.sending": "Sending…",
  "pw.changeBtn": "Change Password",
  "pw.changing": "Changing…",
  "pw.newCode": "Request New Code",
  "editProfile.title": "Edit Profile",
  "editProfile.name": "Name",
  "editProfile.plate": "License Plate",
  "logout.confirm": "Really sign out?",
  "logout.yes": "Sign Out",
  "logout.cancel": "Cancel",
  "coming.soon": "Coming Soon",
  "coming.soon.desc": "This feature will be available in a future version.",
  "contact.email": "support@fahrtdoc.de",
  "contact.title": "Contact",
  "contact.text": "We are happy to help you with any questions or issues.",
  "contact.emailLabel": "Email Support",
  "contact.websiteLabel": "Website",
  "home.greeting": "Hello,",
  "home.defaultDriver": "Driver",
  "home.quickStart": "Quick Start",
  "home.businessTrip": "Business Trip",
  "home.businessSub": "Work & Service",
  "home.privateTrip": "Private Trip",
  "home.privateSub": "Personal",
  "home.gpsBlocked": "GPS blocked – Simulation active",
  "home.stats": "Statistics",
  "home.period.1": "1 Mo.",
  "home.period.3": "3 Mo.",
  "home.period.6": "6 Mo.",
  "home.period.12": "This Year",
  "home.totalKm": "Total km",
  "home.trips": "Trips",
  "home.driveDuration": "Drive Time",
  "home.businessShort": "Business",
  "home.privateShort": "Private",
  "home.distribution": "Trip Distribution",
  "home.recentTrips": "Recent Trips",
  "home.noTrips": "No trips in this period",
  "home.startTripSuffix": "start?",
  "home.modalSub": "GPS will be activated and the route recorded automatically.",
  "home.startBtn": "Start Trip",
  "history.today": "Today",
  "history.yesterday": "Yesterday",
  "history.resetFilter": "Reset Filters",
  "history.dateRange": "Date Range",
  "history.all": "All",
  "history.lastMonth": "Last Month",
  "history.threeMonths": "3 Months",
  "history.sixMonths": "6 Months",
  "history.thisYear": "This Year",
  "history.from": "From",
  "history.to": "To",
  "history.datePlaceholder": "DD.MM.YYYY",
  "history.clearFilter": "Clear Filter",
  "history.selected": "selected",
  "history.totalDistance": "Total Distance",
  "history.selection": "Selection",
  "history.of": "of",
  "history.noSelection": "No Trips Selected",
  "history.noSelectionMsg": "Please select at least one trip or exit selection mode.",
  "history.noTripsTitle": "No Trips",
  "history.noTripsMsg": "No trips for the selected filter.",
  "history.selectAll": "All",
  "history.selectNone": "None",
  "auth.tagline": "Drive simple, log smart",
  "auth.login": "Sign In",
  "auth.register": "Register",
  "auth.fullName": "Full Name",
  "auth.password": "Password",
  "auth.forgotPassword": "Forgot password?",
  "auth.createAccount": "Create Account",
  "auth.error.allFields": "Please fill in all fields.",
  "auth.error.shortPassword": "Password must be at least 6 characters.",
  "auth.error.emailPassword": "Please enter email and password.",
  "auth.error.emailExists": "This email address is already registered.",
  "auth.error.notFound": "No account found with this email address.",
  "auth.error.wrongPassword": "Wrong password. Please try again.",
  "auth.hint.login": "No account yet? Register now.",
  "auth.hint.register": "All data is stored locally.",
  "auth.emailLabel": "E-Mail",
  "auth.emailPlaceholder": "email@example.com",
  "auth.namePlaceholder": "John Smith",
  "auth.platePlaceholder": "AB-CD 1234",
  "error.title": "Error",
  "error.nameRequired": "Please enter a name.",
  "pw.error.noCode": "Please enter the code.",
  "pw.error.tooShort": "Password must be at least 8 characters.",
  "pw.error.mismatch": "Passwords do not match.",
  "pw.error.sendFailed": "Failed to send code.",
  "pw.error.invalid": "Invalid code or error.",
  "pw.success.title": "Success",
  "pw.success.text": "Your password has been changed.",
  "pause.dialog.title": "Record stop?",
  "pause.dialog.message": "Do you want to save your current location as a waypoint?",
  "pause.withWaypoint": "Yes, save as waypoint",
  "pause.withoutWaypoint": "No, just pause",
  "waypoint.label": "Waypoint",
  "waypoint.addressUnavailable": "Address unavailable",
  "waypoint.locating": "Locating…",
  "waypoint.note.title": "Note for this stop",
  "waypoint.note.placeholder": "e.g. Client visit, charging stop …",
  "waypoint.note.confirm": "Save stop",
  "waypoint.note.skip": "Save without note",
  "trip.syncPending": "Route sync",
  "trip.syncRetrying": "Syncing…",
};

const translations: Record<Language, Record<string, string>> = { de, en };

interface LanguageContextType {
  language: Language;
  setLanguage: (l: Language) => Promise<void>;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType>({
  language: "de",
  setLanguage: async () => {},
  t: (key) => de[key] ?? key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLang] = useState<Language>("de");

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then((v) => {
      if (v === "de" || v === "en") setLang(v);
    });
  }, []);

  const setLanguage = useCallback(async (l: Language) => {
    setLang(l);
    await AsyncStorage.setItem(LANG_KEY, l);
  }, []);

  const t = useCallback(
    (key: string) => translations[language][key] ?? translations["de"][key] ?? key,
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
