import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "de" | "en";
const LANG_KEY = "pref_language";

const de: Record<string, string> = {
  "nav.home": "Übersicht",
  "nav.trips": "Fahrten",
  "nav.profile": "Profil",
  "common.save": "Speichern",
  "common.cancel": "Abbrechen",
  "common.done": "Fertig",
  "common.edit": "Bearbeiten",
  "common.close": "Schließen",
  "profile.title": "Profil",
  "profile.editBtn": "Profil bearbeiten",
  "profile.plate": "Kennzeichen",
  "profile.account": "Konto",
  "profile.sync": "Sync",
  "profile.synced": "Synchronisiert",
  "profile.offline": "Offline",
  "profile.premium": "Premium",
  "section.account": "Konto",
  "section.subscription": "Abonnement",
  "section.tracking": "Tracking & Fahrterkennung",
  "section.settings": "Einstellungen",
  "section.security": "Sicherheit & Datenschutz",
  "section.support": "Support",
  "row.subscriptionStatus": "Status",
  "row.manageSubscription": "Abo verwalten",
  "row.upgradePremium": "Premium freischalten",
  "row.restorePurchases": "Käufe wiederherstellen",
  "sub.active": "Aktiv",
  "driveDetect.statusActive": "Aktiv",
  "driveDetect.statusStopped": "Gestoppt",
  "sub.free": "Kostenlos",
  "sub.restoreSuccess": "Wiederhergestellt",
  "sub.restoreSuccessMsg": "Dein Abo wurde erfolgreich wiederhergestellt.",
  "sub.restoreError": "Fehler",
  "sub.restoreErrorMsg": "Kein aktives Abo gefunden.",
  "row.personalData": "Persönliche Daten",
  "row.vehicleProfile": "Fahrprofil & Fahrzeugdaten",
  "row.autoTracking": "Automatisches Tracking",
  "row.autoTracking.desc": "Fahrten automatisch erkennen und aufzeichnen",
  "row.gpsTracking": "GPS-Tracking",
  "row.gpsTracking.desc": "Standort während einer Fahrt erfassen",
  "row.bgTracking": "Hintergrund-Tracking",
  "row.bgTracking.desc": "Fahrten auch bei geschlossener App erkennen",
  "row.offline": "Offline-Speicherung",
  "row.offline.desc": "Fahrten ohne Internet zwischenspeichern",
  "row.pauseTracking": "Tracking pausieren",
  "row.pauseTracking.desc": "Aufzeichnung vorübergehend deaktivieren",
  "row.notifications": "Benachrichtigungen",
  "row.defaultTripType": "Standard-Fahrtart",
  "row.language": "Sprache",
  "row.design": "Design",
  "row.changePassword": "Passwort ändern",
  "row.changeEmail": "E-Mail-Adresse ändern",
  "row.privacy": "Datenschutz",
  "row.faceId": "Face ID / App-Sperre",
  "row.faq": "Hilfe & FAQ",
  "row.contact": "Kontakt",
  "row.appVersion": "App-Version",
  "row.logout": "Abmelden",
  "row.deleteAccount": "Konto löschen",
  "deleteAccount.title": "Konto unwiderruflich löschen?",
  "deleteAccount.message": "Alle deine Fahrten, dein Profil und alle Kontodaten werden sofort und dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
  "deleteAccount.confirm": "Ja, Konto löschen",
  "deleteAccount.cancel": "Abbrechen",
  "deleteAccount.error": "Konto konnte nicht gelöscht werden. Bitte versuche es erneut.",
  "tripType.business": "Geschäftlich",
  "tripType.private": "Privat",
  "theme.light": "Hell",
  "theme.dark": "Dunkel",
  "theme.system": "Systemeinstellung",
  "lang.de": "Deutsch",
  "lang.en": "Englisch",
  "lang.title": "Sprache wählen",
  "vehicle.title": "Fahrprofil & Fahrzeugdaten",
  "vehicle.brand": "Marke",
  "vehicle.model": "Modell",
  "vehicle.year": "Baujahr",
  "vehicle.color": "Farbe",
  "vehicle.plate": "Kennzeichen",
  "vehicle.brandPlaceholder": "z. B. BMW, VW, Mercedes",
  "vehicle.modelPlaceholder": "z. B. 3er, Golf, C-Klasse",
  "vehicle.yearPlaceholder": "z. B. 2022",
  "vehicle.colorPlaceholder": "z. B. Schwarz, Weiß, Blau",
  "notif.title": "Benachrichtigungen",
  "notif.general": "Allgemeine Hinweise",
  "notif.general.desc": "App-Updates und allgemeine Infos",
  "notif.trips": "Fahrten-Erinnerungen",
  "notif.trips.desc": "Hinweise zu offenen oder unvollständigen Fahrten",
  "notif.tracking": "Automatische Tracking-Hinweise",
  "notif.tracking.desc": "Statusmeldungen bei automatischer Fahrterkennung",
  "notif.gps": "GPS-Status",
  "notif.gps.desc": "Warnungen bei schwachem oder fehlendem GPS-Signal",
  "notif.offline": "Offline-Modus",
  "notif.offline.desc": "Hinweise bei fehlender Internetverbindung",
  "notif.sync": "Synchronisation",
  "notif.sync.desc": "Meldungen zu Datensynchronisation und Backup",
  "notif.login": "Login & Gerätezugriff",
  "notif.login.desc": "Sicherheitshinweise zu Anmeldungen und Gerätezugriffen",
  "notif.datenschutz": "Datenschutz & App-Sperre",
  "notif.datenschutz.desc": "Hinweise zu Datenschutzeinstellungen und App-Sperre",
  "notif.driveRemind": "Fahrt-Erinnerungen",
  "notif.driveRemind.desc": "Benachrichtigung wenn du anfaengst oder aufhoerst zu fahren",
  "notif.stoppedThreshold": "Warnung nach Stopp",
  "notif.stoppedThreshold.desc": "Wie lange die Fahrterkennung gestoppt sein muss, bevor eine Warnung erscheint",
  "notif.stoppedThreshold.min2": "2 Min.",
  "notif.stoppedThreshold.min5": "5 Min.",
  "notif.stoppedThreshold.min10": "10 Min.",
  "privacy.title": "Datenschutz",
  "faq.title": "Hilfe & FAQ",
  "settings.title": "Einstellungen",
  "pw.step1": "Code anfordern",
  "pw.step2": "Code & Passwort",
  "pw.sendCode": "Code per E-Mail senden",
  "pw.sending": "Senden…",
  "pw.changeBtn": "Passwort ändern",
  "pw.changing": "Wird geändert…",
  "pw.newCode": "Neuen Code anfordern",
  "em.step1": "Neue E-Mail eingeben",
  "em.step2": "Code bestätigen",
  "em.newEmailLabel": "Neue E-Mail-Adresse",
  "em.newEmailPlaceholder": "neue@email.de",
  "em.sendCode": "Code anfordern",
  "em.sending": "Wird gesendet…",
  "em.changeBtn": "E-Mail-Adresse ändern",
  "em.changing": "Wird geändert…",
  "em.newCode": "Neuen Code anfordern",
  "em.info": "Ein Bestätigungscode wird an deine aktuelle E-Mail-Adresse gesendet.",
  "em.error.noEmail": "Bitte gib eine neue E-Mail-Adresse ein.",
  "em.error.invalidEmail": "Bitte gib eine gültige E-Mail-Adresse ein.",
  "em.error.noCode": "Bitte gib den Code ein.",
  "em.error.sendFailed": "Fehler beim Senden des Codes.",
  "em.error.invalid": "Ungültiger Code oder Fehler.",
  "em.success.title": "E-Mail geändert",
  "em.success.text": "Deine E-Mail-Adresse wurde geändert. Bitte melde dich erneut an.",
  "editProfile.title": "Profil bearbeiten",
  "editProfile.name": "Name",
  "editProfile.plate": "Kennzeichen",
  "logout.confirm": "Wirklich abmelden?",
  "logout.yes": "Abmelden",
  "logout.cancel": "Abbrechen",
  "coming.soon": "Demnächst",
  "coming.soon.desc": "Diese Funktion wird in einer zukünftigen Version verfügbar sein.",
  "contact.email": "info@centofai.com",
  "contact.title": "Kontakt",
  "contact.text": "Bei Fragen oder Problemen stehen wir dir gerne zur Verfügung.",
  "contact.emailLabel": "E-Mail Support",
  "contact.websiteLabel": "Website",
  "home.greeting": "Willkommen zurück,",
  "home.defaultDriver": "Fahrer",
  "home.quickStart": "Schnellstart",
  "home.businessTrip": "Geschäftsreise",
  "home.businessSub": "Arbeit & Dienst",
  "home.privateTrip": "Private Fahrt",
  "home.privateSub": "Persönlich",
  "home.gpsBlocked": "GPS blockiert – Simulation aktiv",
  "home.stats": "Statistiken",
  "home.period.1": "1 Mon.",
  "home.period.3": "3 Mon.",
  "home.period.6": "6 Mon.",
  "home.period.12": "Dieses Jahr",
  "home.totalKm": "Gesamt km",
  "home.trips": "Fahrten",
  "home.driveDuration": "Fahrzeit",
  "home.businessShort": "Geschäftl.",
  "home.privateShort": "Privat",
  "home.distribution": "Zweckverteilung",
  "home.recentTrips": "Letzte Fahrten",
  "home.noTrips": "Keine Fahrten in diesem Zeitraum",
  "home.startTripSuffix": "starten?",
  "home.modalSub": "GPS wird aktiviert und die Strecke automatisch aufgezeichnet.",
  "home.startBtn": "Fahrt starten",
  "home.activePillTooltip": "Automatische Fahrterkennung aktiv – tippen zum Verwalten",
  "home.suggested": "Empfohlen",
  "history.today": "Heute",
  "history.yesterday": "Gestern",
  "history.resetFilter": "Filter zurücksetzen",
  "history.dateRange": "Von – Bis",
  "history.all": "Alle",
  "history.lastMonth": "Letzter Monat",
  "history.threeMonths": "3 Monate",
  "history.sixMonths": "6 Monate",
  "history.thisYear": "Dieses Jahr",
  "history.from": "Von",
  "history.to": "Bis",
  "history.datePlaceholder": "TT.MM.JJJJ",
  "history.clearFilter": "Filter löschen",
  "history.selected": "ausgewählt",
  "history.totalDistance": "Gesamtstrecke",
  "history.selection": "Auswahl",
  "history.of": "von",
  "history.noSelection": "Keine Fahrten ausgewählt",
  "history.noSelectionMsg": "Bitte wähle mindestens eine Fahrt aus oder verlasse den Auswahlmodus.",
  "history.noTripsTitle": "Keine Fahrten",
  "history.noTripsMsg": "Keine Fahrten für den gewählten Filter.",
  "history.selectAll": "Alle",
  "history.selectNone": "Keine",
  "history.pickMonth": "Monat wählen",
  "history.syncing": "Wird sync…",
  "history.exportCSV": "Als CSV exportieren",
  "history.exportCSVEmpty": "Keine Fahrten",
  "history.exportCSVEmptyMsg": "Es gibt keine Fahrten für den gewählten Zeitraum.",
  "history.splitExport": "Split",
  "history.splitConfirmTitle": "Export bestätigen",
  "history.splitConfirmBtn": "Exportieren",
  "history.splitCancel": "Abbrechen",
  "history.splitBusiness": "geschäftliche Fahrten",
  "history.splitPrivate": "private Fahrten",
  "history.splitNoPrivate": "Keine privaten Fahrten — nur das Geschäftsreise-PDF wird erstellt.",
  "history.splitNoBusiness": "Keine geschäftlichen Fahrten — nur das Privatreise-PDF wird erstellt.",
  "trip.delete.title": "Fahrt löschen?",
  "trip.delete.message": "Diese Fahrt wird unwiderruflich gelöscht.",
  "trip.delete.confirm": "Löschen",
  "trip.delete.cancel": "Abbrechen",
  "auth.tagline": "Einfach fahren, clever erfassen",
  "auth.login": "Anmelden",
  "auth.register": "Registrieren",
  "auth.fullName": "Vollständiger Name",
  "auth.password": "Passwort",
  "auth.forgotPassword": "Passwort vergessen?",
  "auth.createAccount": "Konto erstellen",
  "auth.error.allFields": "Bitte alle Felder ausfüllen.",
  "auth.error.shortPassword": "Passwort muss mindestens 6 Zeichen lang sein.",
  "auth.error.emailPassword": "Bitte E-Mail und Passwort eingeben.",
  "auth.error.emailExists": "Diese E-Mail-Adresse ist bereits registriert.",
  "auth.error.notFound": "Kein Konto mit dieser E-Mail-Adresse gefunden.",
  "auth.error.wrongPassword": "Falsches Passwort. Bitte versuche es erneut.",
  "auth.error.serverUnavailable": "Server nicht erreichbar. Bitte Internetverbindung prüfen.",
  "auth.hint.login": "Noch kein Konto? Jetzt registrieren.",
  "auth.hint.register": "Alle Daten werden lokal gespeichert.",
  "auth.emailLabel": "E-Mail",
  "auth.emailPlaceholder": "email@beispiel.de",
  "auth.namePlaceholder": "Max Mustermann",
  "auth.platePlaceholder": "B-DL 1234",
  "error.title": "Fehler",
  "error.nameRequired": "Bitte gib einen Namen ein.",
  "pw.error.noCode": "Bitte gib den Code ein.",
  "pw.error.tooShort": "Das Passwort muss mindestens 8 Zeichen haben.",
  "pw.error.mismatch": "Die Passwoerter stimmen nicht ueberein.",
  "pw.error.sendFailed": "Fehler beim Senden des Codes.",
  "pw.error.invalid": "Ungueltiger Code oder Fehler.",
  "pw.success.title": "Erfolg",
  "pw.success.text": "Dein Passwort wurde geaendert.",
  "edit.title": "Fahrt bearbeiten",
  "edit.tripPurpose": "Fahrtzweck",
  "edit.startAddr": "Startadresse",
  "edit.endAddr": "Zieladresse",
  "edit.addrPlaceholder": "Adresse",
  "edit.notePlaceholder": "Notiz (optional)",
  "edit.distanceKm": "Strecke (km)",
  "edit.durationMin": "Dauer (Min)",
  "edit.saveChanges": "Änderungen speichern",
  "edit.pinStart": "Start pinnen",
  "edit.pinEnd": "Ziel pinnen",
  "edit.pinned": "Gepinnt",
  "pin.hint": "Tippe auf die Karte oder suche eine Adresse, um den Pin zu setzen. Ziehen zum Anpassen.",
  "pin.hint.native": "Adresse suchen und aus den Vorschlägen wählen.",
  "pin.searchPlaceholder": "Adresse suchen …",
  "pin.searchError": "Keine Ergebnisse gefunden.",
  "pin.confirm": "Position bestätigen",
  "detail.routeLabel": "FAHRTROUTE",
  "detail.stationsLabel": "STATIONEN",
  "detail.start": "Start",
  "detail.startUnknown": "Startpunkt unbekannt",
  "detail.end": "Ziel",
  "detail.endUnknown": "Zielpunkt unbekannt",
  "detail.distance": "Strecke",
  "detail.driveTime": "Fahrzeit",
  "detail.stop": "Stopp",
  "detail.stops": "Stopps",
  "detail.edited": "Bearbeitet",
  "detail.noteLabel": "NOTIZ",
  "detail.notePlaceholder": "Notiz zur Fahrt hinzufügen …",
  "detail.noteSaved": "Gespeichert",
  "save.title": "Fahrt beenden",
  "save.subtitle": "Adressen tippen zum Bearbeiten",
  "save.addressLoading": "Wird ermittelt …",
  "save.kmSection": "KILOMETERSTAND WÄHLEN",
  "save.gpsKmLabel": "Gefahrene Kilometer",
  "save.gpsKmSub": "GPS-aufgezeichnete Strecke",
  "save.loadingRoutes": "Routen werden berechnet …",
  "save.routeError": "Routen konnten nicht geladen werden",
  "save.badgeShortest": "Kürzeste",
  "save.badgeFastest": "Schnellste",
  "save.routeDurationSuffix": "min Fahrzeit",
  "save.useRouteDuration": "Fahrzeit aus Route übernehmen",
  "save.useRouteDurationSub": "Ersetzt die GPS-gemessene Fahrzeit",
  "save.confirmTitle": "Fahrt speichern?",
  "save.confirmMessage": "Die Fahrt wird mit den gewählten Kilometern gespeichert.",
  "save.discardTitle": "Fahrt verwerfen?",
  "save.discardMessage": "Die aufgezeichnete Fahrt wird gelöscht und nicht gespeichert.",
  "save.discardBack": "Zurück",
  "save.discardBtn": "Verwerfen",
  "pause.dialog.title": "Zwischenstopp erfassen?",
  "pause.dialog.message": "Möchtest du den aktuellen Standort als Zwischenstopp speichern?",
  "pause.withWaypoint": "Ja, als Zwischenstopp speichern",
  "pause.withoutWaypoint": "Nein, nur pausieren",
  "waypoint.label": "Zwischenstopp",
  "waypoint.addressUnavailable": "Adresse nicht verfügbar",
  "waypoint.locating": "Standort wird ermittelt…",
  "waypoint.note.title": "Notiz zum Stopp",
  "waypoint.note.placeholder": "z. B. Kundenbesuch, Ladestation …",
  "waypoint.note.confirm": "Stopp speichern",
  "waypoint.note.skip": "Ohne Notiz speichern",
  "trip.note.title": "Notiz",
  "trip.note.delete": "Notiz löschen",
  "trip.dur.min": "Min",
  "trip.dur.h": "h",
  "trip.syncPending": "Route sync",
  "trip.syncRetrying": "Wird sync…",
  "trip.syncFailed": "Sync fehlgeschlagen – bitte erneut versuchen",
  "export.error.title": "Exportfehler",
  "export.error.storage": "Nicht genug Speicherplatz. Bitte gib Speicher frei und versuche es erneut.",
  "export.error.permission": "Kein Zugriff auf den Speicher. Bitte prüfe die App-Berechtigungen.",
  "export.error.unknown": "Export fehlgeschlagen. Bitte versuche es erneut.",
  "export.error.retry": "Erneut versuchen",
  "section.export": "Export-Einstellungen",
  "row.signatureBlock": "Unterschriftsfeld im PDF",
  "row.signatureBlock.desc": "Fügt einen datierten Unterschriftsblock am Ende des PDFs hinzu",
  "row.refreshAddresses": "Adressen aktualisieren",
  "row.refreshAddresses.desc": "Ergänzt fehlende Hausnummern in gespeicherten Fahrten",
  "row.refreshAddresses.running": "Adressen werden aktualisiert …",
  "row.refreshAddresses.done": "Adressen aktualisiert",
  "row.companyInfo": "Unternehmensinfos",
  "company.modal.title": "Unternehmensinfos",
  "company.name.label": "Firmenname",
  "company.name.placeholder": "z. B. Mustermann GmbH",
  "company.logo.label": "Firmenlogo",
  "company.logo.pick": "Logo auswählen",
  "company.logo.change": "Logo ändern",
  "company.logo.remove": "Logo entfernen",
  "company.logo.hint": "Erscheint im Kopf des exportierten PDFs",
  "tracking.paused": "PAUSIERT",
  "tracking.active": "FAHRT LÄUFT",
  "tracking.gpsOff": "GPS deaktiviert — Daten manuell erfassen",
  "tracking.driveDetectStopped": "Fahrterkennung gestoppt",
  "tracking.restartDetect": "Neu starten",
  "tracking.carplaySource": "Gestartet über CarPlay",
  "tracking.androidAutoSource": "Gestartet über Android Auto",
  "tracking.carplayStopSource": "Gestoppt über CarPlay",
  "watchdog.title": "FahrtDoc – Fahrterkennung gestoppt",
  "watchdog.body": "Die automatische Fahrterkennung wurde unterbrochen. Bitte App öffnen um die Fahrt zu sichern.",
  "driveNotif.startTitle": "FahrtDoc – Fahrt dokumentieren?",
  "driveNotif.startBody": "Du fährst — möchtest du diese Fahrt aufzeichnen?",
  "driveNotif.stopTitle": "FahrtDoc – Fahrt beenden?",
  "driveNotif.stopBody": "Du scheinst geparkt zu haben — Fahrt jetzt beenden?",
  "tracking.screen.title": "Fahrt läuft",
  "tracking.screen.elapsed": "Fahrzeit",
  "tracking.screen.distance": "Strecke",
  "tracking.screen.waypoints": "Stopps",
  "tracking.screen.from": "Von",
  "tracking.screen.pause": "Pausieren",
  "tracking.screen.resume": "Fortsetzen",
  "tracking.screen.stop": "Fahrt stoppen",
  "tracking.screen.pausedNote": "Fahrt ist pausiert — Stopp wird nicht erfasst.",
  "tracking.screen.waitingGps": "Warte auf GPS-Signal",
  "tracking.screen.waitingGpsSub": "Karte erscheint sobald eine Position verfügbar ist.",
  "tracking.screen.gpsOff": "GPS deaktiviert",
  "tracking.screen.gpsOffSub": "Strecke wird anhand von Fahrtzeit und Geschwindigkeit geschätzt.",
  "tracking.screen.addNote": "Notiz hinzufügen",
  "tracking.screen.notePlaceholder": "z. B. Kundenbesuch, Dienstreise …",
  "save.noteSection": "NOTIZ",
  "save.notePlaceholder": "Notiz zur Fahrt (optional) …",
  "forgot.title": "Passwort vergessen?",
  "forgot.subtitle": "Gib deine E-Mail-Adresse ein. Wir senden dir einen 6-stelligen Code zur Wiederherstellung.",
  "forgot.emailLabel": "E-Mail-Adresse",
  "forgot.sendCode": "Code senden",
  "forgot.infoBox": "Der Code ist 5 Minuten gültig. In der Produktionsversion wird er per E-Mail zugestellt.",
  "forgot.backToLogin": "Zurück zur Anmeldung",
  "forgot.error.invalidEmail": "Bitte eine gültige E-Mail-Adresse eingeben.",
  "forgot.error.unknown": "Unbekannter Fehler.",
  "forgot.error.serverError": "Verbindung zum Server fehlgeschlagen. Bitte versuche es erneut.",
};

const en: Record<string, string> = {
  "nav.home": "Overview",
  "nav.trips": "Trips",
  "nav.profile": "Profile",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.done": "Done",
  "common.edit": "Edit",
  "common.close": "Close",
  "profile.title": "Profile",
  "profile.editBtn": "Edit Profile",
  "profile.plate": "License Plate",
  "profile.account": "Account",
  "profile.sync": "Sync",
  "profile.synced": "Synced",
  "profile.offline": "Offline",
  "profile.premium": "Premium",
  "section.account": "Account",
  "section.subscription": "Subscription",
  "section.tracking": "Tracking & Trip Detection",
  "section.settings": "Settings",
  "section.security": "Security & Privacy",
  "section.support": "Support",
  "row.subscriptionStatus": "Status",
  "row.manageSubscription": "Manage Subscription",
  "row.upgradePremium": "Unlock Premium",
  "row.restorePurchases": "Restore Purchases",
  "sub.active": "Active",
  "driveDetect.statusActive": "Active",
  "driveDetect.statusStopped": "Stopped",
  "sub.free": "Free",
  "sub.restoreSuccess": "Restored",
  "sub.restoreSuccessMsg": "Your subscription has been successfully restored.",
  "sub.restoreError": "Error",
  "sub.restoreErrorMsg": "No active subscription found.",
  "row.personalData": "Personal Data",
  "row.vehicleProfile": "Driving Profile & Vehicle Data",
  "row.autoTracking": "Automatic Tracking",
  "row.autoTracking.desc": "Automatically detect and record trips",
  "row.gpsTracking": "GPS Tracking",
  "row.gpsTracking.desc": "Record location during a trip",
  "row.bgTracking": "Background Tracking",
  "row.bgTracking.desc": "Detect trips even when the app is closed",
  "row.offline": "Offline Storage",
  "row.offline.desc": "Save trips without internet connection",
  "row.pauseTracking": "Pause Tracking",
  "row.pauseTracking.desc": "Temporarily disable recording",
  "row.notifications": "Notifications",
  "row.defaultTripType": "Default Trip Type",
  "row.language": "Language",
  "row.design": "Appearance",
  "row.changePassword": "Change Password",
  "row.privacy": "Privacy",
  "row.faceId": "Face ID / App Lock",
  "row.faq": "Help & FAQ",
  "row.contact": "Contact",
  "row.appVersion": "App Version",
  "row.logout": "Sign Out",
  "row.deleteAccount": "Delete Account",
  "deleteAccount.title": "Permanently delete account?",
  "deleteAccount.message": "All your trips, profile and account data will be immediately and permanently deleted. This action cannot be undone.",
  "deleteAccount.confirm": "Yes, delete account",
  "deleteAccount.cancel": "Cancel",
  "deleteAccount.error": "Account could not be deleted. Please try again.",
  "tripType.business": "Business",
  "tripType.private": "Private",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "theme.system": "System",
  "lang.de": "German",
  "lang.en": "English",
  "lang.title": "Choose Language",
  "vehicle.title": "Driving Profile & Vehicle Data",
  "vehicle.brand": "Brand",
  "vehicle.model": "Model",
  "vehicle.year": "Year",
  "vehicle.color": "Color",
  "vehicle.plate": "License Plate",
  "vehicle.brandPlaceholder": "e.g. BMW, VW, Mercedes",
  "vehicle.modelPlaceholder": "e.g. 3 Series, Golf, C-Class",
  "vehicle.yearPlaceholder": "e.g. 2022",
  "vehicle.colorPlaceholder": "e.g. Black, White, Blue",
  "notif.title": "Notifications",
  "notif.general": "General Notices",
  "notif.general.desc": "App updates and general info",
  "notif.trips": "Trip Reminders",
  "notif.trips.desc": "Notices for open or incomplete trips",
  "notif.tracking": "Auto Tracking Notices",
  "notif.tracking.desc": "Status updates for automatic trip detection",
  "notif.gps": "GPS Status",
  "notif.gps.desc": "Warnings for weak or missing GPS signal",
  "notif.offline": "Offline Mode",
  "notif.offline.desc": "Notices when internet connection is unavailable",
  "notif.sync": "Synchronization",
  "notif.sync.desc": "Messages about data sync and backup",
  "notif.login": "Login & Device Access",
  "notif.login.desc": "Security notices for logins and device access",
  "notif.datenschutz": "Privacy & App Lock",
  "notif.datenschutz.desc": "Notices about privacy settings and app lock",
  "notif.driveRemind": "Drive Reminders",
  "notif.driveRemind.desc": "Notification when you start or stop driving",
  "notif.stoppedThreshold": "Warn after stopped",
  "notif.stoppedThreshold.desc": "How long detection must be stopped before a warning appears",
  "notif.stoppedThreshold.min2": "2 min",
  "notif.stoppedThreshold.min5": "5 min",
  "notif.stoppedThreshold.min10": "10 min",
  "privacy.title": "Privacy",
  "faq.title": "Help & FAQ",
  "settings.title": "Settings",
  "pw.step1": "Request Code",
  "pw.step2": "Code & Password",
  "pw.sendCode": "Send Code by Email",
  "pw.sending": "Sending…",
  "pw.changeBtn": "Change Password",
  "pw.changing": "Changing…",
  "pw.newCode": "Request New Code",
  "em.step1": "Enter New Email",
  "em.step2": "Confirm Code",
  "em.newEmailLabel": "New Email Address",
  "em.newEmailPlaceholder": "new@email.com",
  "em.sendCode": "Request Code",
  "em.sending": "Sending…",
  "em.changeBtn": "Change Email Address",
  "em.changing": "Changing…",
  "em.newCode": "Request New Code",
  "em.info": "A confirmation code will be sent to your current email address.",
  "em.error.noEmail": "Please enter a new email address.",
  "em.error.invalidEmail": "Please enter a valid email address.",
  "em.error.noCode": "Please enter the code.",
  "em.error.sendFailed": "Error sending the code.",
  "em.error.invalid": "Invalid code or error.",
  "em.success.title": "Email Changed",
  "em.success.text": "Your email address has been changed. Please sign in again.",
  "row.changeEmail": "Change Email Address",
  "editProfile.title": "Edit Profile",
  "editProfile.name": "Name",
  "editProfile.plate": "License Plate",
  "logout.confirm": "Really sign out?",
  "logout.yes": "Sign Out",
  "logout.cancel": "Cancel",
  "coming.soon": "Coming Soon",
  "coming.soon.desc": "This feature will be available in a future version.",
  "contact.email": "info@centofai.com",
  "contact.title": "Contact",
  "contact.text": "We are happy to help you with any questions or issues.",
  "contact.emailLabel": "Email Support",
  "contact.websiteLabel": "Website",
  "home.greeting": "Welcome back,",
  "home.defaultDriver": "Driver",
  "home.quickStart": "Quick Start",
  "home.businessTrip": "Business Trip",
  "home.businessSub": "Work & Service",
  "home.privateTrip": "Private Trip",
  "home.privateSub": "Personal",
  "home.gpsBlocked": "GPS blocked – Simulation active",
  "home.stats": "Statistics",
  "home.period.1": "1 Mo.",
  "home.period.3": "3 Mo.",
  "home.period.6": "6 Mo.",
  "home.period.12": "This Year",
  "home.totalKm": "Total km",
  "home.trips": "Trips",
  "home.driveDuration": "Drive Time",
  "home.businessShort": "Business",
  "home.privateShort": "Private",
  "home.distribution": "Trip Distribution",
  "home.recentTrips": "Recent Trips",
  "home.noTrips": "No trips in this period",
  "home.startTripSuffix": "start?",
  "home.modalSub": "GPS will be activated and the route recorded automatically.",
  "home.startBtn": "Start Trip",
  "home.activePillTooltip": "Auto drive detection active – tap to manage",
  "home.suggested": "Suggested",
  "history.today": "Today",
  "history.yesterday": "Yesterday",
  "history.resetFilter": "Reset Filters",
  "history.dateRange": "Date Range",
  "history.all": "All",
  "history.lastMonth": "Last Month",
  "history.threeMonths": "3 Months",
  "history.sixMonths": "6 Months",
  "history.thisYear": "This Year",
  "history.from": "From",
  "history.to": "To",
  "history.datePlaceholder": "DD.MM.YYYY",
  "history.clearFilter": "Clear Filter",
  "history.selected": "selected",
  "history.totalDistance": "Total Distance",
  "history.selection": "Selection",
  "history.of": "of",
  "history.noSelection": "No Trips Selected",
  "history.noSelectionMsg": "Please select at least one trip or exit selection mode.",
  "history.noTripsTitle": "No Trips",
  "history.noTripsMsg": "No trips for the selected filter.",
  "history.selectAll": "All",
  "history.selectNone": "None",
  "history.pickMonth": "Pick Month",
  "history.syncing": "Syncing…",
  "history.exportCSV": "Export as CSV",
  "history.exportCSVEmpty": "No Trips",
  "history.exportCSVEmptyMsg": "There are no trips for the selected period.",
  "history.splitExport": "Split",
  "history.splitConfirmTitle": "Confirm Export",
  "history.splitConfirmBtn": "Export",
  "history.splitCancel": "Cancel",
  "history.splitBusiness": "business trips",
  "history.splitPrivate": "private trips",
  "history.splitNoPrivate": "No private trips — only the business mileage PDF will be created.",
  "history.splitNoBusiness": "No business trips — only the private mileage PDF will be created.",
  "trip.delete.title": "Delete trip?",
  "trip.delete.message": "This trip will be permanently deleted.",
  "trip.delete.confirm": "Delete",
  "trip.delete.cancel": "Cancel",
  "auth.tagline": "Drive simple, log smart",
  "auth.login": "Sign In",
  "auth.register": "Register",
  "auth.fullName": "Full Name",
  "auth.password": "Password",
  "auth.forgotPassword": "Forgot password?",
  "auth.createAccount": "Create Account",
  "auth.error.allFields": "Please fill in all fields.",
  "auth.error.shortPassword": "Password must be at least 6 characters.",
  "auth.error.emailPassword": "Please enter email and password.",
  "auth.error.emailExists": "This email address is already registered.",
  "auth.error.notFound": "No account found with this email address.",
  "auth.error.wrongPassword": "Wrong password. Please try again.",
  "auth.error.serverUnavailable": "Server unavailable. Please check your internet connection.",
  "auth.hint.login": "No account yet? Register now.",
  "auth.hint.register": "All data is stored locally.",
  "auth.emailLabel": "E-Mail",
  "auth.emailPlaceholder": "email@example.com",
  "auth.namePlaceholder": "John Smith",
  "auth.platePlaceholder": "AB-CD 1234",
  "error.title": "Error",
  "error.nameRequired": "Please enter a name.",
  "pw.error.noCode": "Please enter the code.",
  "pw.error.tooShort": "Password must be at least 8 characters.",
  "pw.error.mismatch": "Passwords do not match.",
  "pw.error.sendFailed": "Failed to send code.",
  "pw.error.invalid": "Invalid code or error.",
  "pw.success.title": "Success",
  "pw.success.text": "Your password has been changed.",
  "edit.title": "Edit Trip",
  "edit.tripPurpose": "Trip Purpose",
  "edit.startAddr": "Start Address",
  "edit.endAddr": "Destination",
  "edit.addrPlaceholder": "Address",
  "edit.notePlaceholder": "Note (optional)",
  "edit.distanceKm": "Distance (km)",
  "edit.durationMin": "Duration (min)",
  "edit.saveChanges": "Save Changes",
  "edit.pinStart": "Pin start",
  "edit.pinEnd": "Pin destination",
  "edit.pinned": "Pinned",
  "pin.hint": "Tap the map or search an address to place the pin. Drag to adjust.",
  "pin.hint.native": "Search for an address and select from the suggestions.",
  "pin.searchPlaceholder": "Search address …",
  "pin.searchError": "No results found.",
  "pin.confirm": "Confirm location",
  "detail.routeLabel": "ROUTE",
  "detail.stationsLabel": "STOPS",
  "detail.start": "Start",
  "detail.startUnknown": "Start location unknown",
  "detail.end": "End",
  "detail.endUnknown": "End location unknown",
  "detail.distance": "Distance",
  "detail.driveTime": "Drive time",
  "detail.stop": "Stop",
  "detail.stops": "Stops",
  "detail.edited": "Edited",
  "detail.noteLabel": "NOTE",
  "detail.notePlaceholder": "Add a note to this trip…",
  "detail.noteSaved": "Saved",
  "save.title": "End Trip",
  "save.subtitle": "Tap addresses to edit",
  "save.addressLoading": "Locating…",
  "save.kmSection": "SELECT MILEAGE",
  "save.gpsKmLabel": "Distance Driven",
  "save.gpsKmSub": "GPS-recorded route",
  "save.loadingRoutes": "Calculating routes…",
  "save.routeError": "Routes could not be loaded",
  "save.badgeShortest": "Shortest",
  "save.badgeFastest": "Fastest",
  "save.routeDurationSuffix": "min drive time",
  "save.useRouteDuration": "Use route duration",
  "save.useRouteDurationSub": "Replaces the GPS-measured duration",
  "save.confirmTitle": "Save trip?",
  "save.confirmMessage": "The trip will be saved with the selected mileage.",
  "save.discardTitle": "Discard trip?",
  "save.discardMessage": "The recorded trip will be deleted and not saved.",
  "save.discardBack": "Back",
  "save.discardBtn": "Discard",
  "pause.dialog.title": "Record stop?",
  "pause.dialog.message": "Do you want to save your current location as a waypoint?",
  "pause.withWaypoint": "Yes, save as waypoint",
  "pause.withoutWaypoint": "No, just pause",
  "waypoint.label": "Waypoint",
  "waypoint.addressUnavailable": "Address unavailable",
  "waypoint.locating": "Locating…",
  "waypoint.note.title": "Note for this stop",
  "waypoint.note.placeholder": "e.g. Client visit, charging stop …",
  "waypoint.note.confirm": "Save stop",
  "waypoint.note.skip": "Save without note",
  "trip.note.title": "Note",
  "trip.note.delete": "Delete note",
  "trip.dur.min": "min",
  "trip.dur.h": "h",
  "trip.syncPending": "Route sync",
  "trip.syncRetrying": "Syncing…",
  "trip.syncFailed": "Sync failed – please try again",
  "export.error.title": "Export Error",
  "export.error.storage": "Not enough storage space. Please free up some space and try again.",
  "export.error.permission": "Storage access denied. Please check app permissions.",
  "export.error.unknown": "Export failed. Please try again.",
  "export.error.retry": "Try Again",
  "section.export": "Export Settings",
  "row.signatureBlock": "Signature Field in PDF",
  "row.signatureBlock.desc": "Adds a dated signature block at the end of the exported PDF",
  "row.refreshAddresses": "Update Addresses",
  "row.refreshAddresses.desc": "Fills in missing house numbers on saved trips",
  "row.refreshAddresses.running": "Updating addresses …",
  "row.refreshAddresses.done": "Addresses updated",
  "row.companyInfo": "Company Info",
  "company.modal.title": "Company Info",
  "company.name.label": "Company Name",
  "company.name.placeholder": "e.g. Smith Consulting Ltd.",
  "company.logo.label": "Company Logo",
  "company.logo.pick": "Choose Logo",
  "company.logo.change": "Change Logo",
  "company.logo.remove": "Remove Logo",
  "company.logo.hint": "Appears in the header of exported PDFs",
  "tracking.paused": "PAUSED",
  "tracking.active": "TRIP ACTIVE",
  "tracking.gpsOff": "GPS off — enter data manually",
  "tracking.driveDetectStopped": "Drive detection stopped",
  "tracking.restartDetect": "Restart",
  "tracking.carplaySource": "Started via CarPlay",
  "tracking.androidAutoSource": "Started via Android Auto",
  "tracking.carplayStopSource": "Stopped via CarPlay",
  "watchdog.title": "FahrtDoc – Drive detection stopped",
  "watchdog.body": "Automatic drive detection was interrupted. Please open the app to save your trip.",
  "driveNotif.startTitle": "FahrtDoc – Record trip?",
  "driveNotif.startBody": "You're driving — would you like to record this trip?",
  "driveNotif.stopTitle": "FahrtDoc – End trip?",
  "driveNotif.stopBody": "Looks like you've parked — end the trip now?",
  "tracking.screen.title": "Trip in progress",
  "tracking.screen.elapsed": "Drive time",
  "tracking.screen.distance": "Distance",
  "tracking.screen.waypoints": "Stops",
  "tracking.screen.from": "From",
  "tracking.screen.pause": "Pause",
  "tracking.screen.resume": "Resume",
  "tracking.screen.stop": "Stop trip",
  "tracking.screen.pausedNote": "Trip is paused — stop is not being recorded.",
  "tracking.screen.waitingGps": "Waiting for GPS signal",
  "tracking.screen.waitingGpsSub": "Map will appear once a position is available.",
  "tracking.screen.gpsOff": "GPS disabled",
  "tracking.screen.gpsOffSub": "Distance is estimated based on drive time and speed.",
  "tracking.screen.addNote": "Add note",
  "tracking.screen.notePlaceholder": "e.g. client visit, business trip …",
  "save.noteSection": "NOTE",
  "save.notePlaceholder": "Note about this trip (optional) …",
  "forgot.title": "Forgot Password?",
  "forgot.subtitle": "Enter your email address. We'll send you a 6-digit recovery code.",
  "forgot.emailLabel": "Email Address",
  "forgot.sendCode": "Send Code",
  "forgot.infoBox": "The code is valid for 5 minutes. In the production version it will be delivered by email.",
  "forgot.backToLogin": "Back to Sign In",
  "forgot.error.invalidEmail": "Please enter a valid email address.",
  "forgot.error.unknown": "Unknown error.",
  "forgot.error.serverError": "Connection to server failed. Please try again.",
};

export const translations: Record<Language, Record<string, string>> = { de, en };

interface LanguageContextType {
  language: Language;
  setLanguage: (l: Language) => Promise<void>;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType>({
  language: "de",
  setLanguage: async () => {},
  t: (key) => de[key] ?? key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLang] = useState<Language>("de");

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then((v) => {
      if (v === "de" || v === "en") setLang(v);
    });
  }, []);

  const setLanguage = useCallback(async (l: Language) => {
    setLang(l);
    await AsyncStorage.setItem(LANG_KEY, l);
  }, []);

  const t = useCallback(
    (key: string) => translations[language][key] ?? translations["de"][key] ?? key,
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
